name: Check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    # ready_for_review is required for pull requests created by robots.
    # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
    # https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

jobs:
  yaml:
    name: Check projects.yaml
    runs-on: ubuntu-latest
    steps:
      - name: Fetch projects.yaml
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            projects.yaml
            justfile
            scripts
          sparse-checkout-cone-mode: false
      
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Install boon and yq
        run: |
          wget https://github.com/santhosh-tekuri/boon/releases/download/v0.6.1/boon-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf boon-x86_64-unknown-linux-gnu.tar.gz
          sudo mv boon /usr/local/bin/boon

          curl -sS https://webi.sh/yq | sh
          source ~/.config/envman/PATH.env
      - run: just bootstrap

      - name: Validate according to the schema
        run: |
          boon scripts/projects.schema.json projects.yaml
      - name: Check the uniqueness
        shell: bash
        run: |
            just check-uniq | tee -a $GITHUB_STEP_SUMMARY
  typ:
    name: Check typst code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: astral-sh/setup-uv@v6
      - uses: typst-community/setup-typst@v4
        with:
          typst-version: v0.14.0

      - run: just build-typ

      - uses: actions/configure-pages@v5
      - uses: actions/upload-artifact@v4
        with:
          name: build-typ
          path: ./build
